[package]
name = "mqtt_to_timescale"
version = "0.2.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
rumqttc = "0.25.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
anyhow = "1.0"
rand = "0.8"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio", "macros"] }
