{
 "title": "SolarPanel",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Energie produite",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ((data->>'energy')::NUMERIC) as values FROM metrics where user_id=3  ORDER BY time DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Haut ballon",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  time,((data->>'temp3')::NUMERIC) as values FROM metrics WHERE user_id=3  ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Bas ballon",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  time,((data->>'temp2')::NUMERIC) as values FROM metrics WHERE user_id=3  ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Wifi signal",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  time,((data->>'wifi')::NUMERIC) as values FROM metrics where user_id=3  ORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Etat de la pompe",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  time,((data->>'pump1')::NUMERIC) as values FROM metrics where user_id=3 ORDER BY time DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Etat de la pompe",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(\"time\",$__interval,previous),AVG(((data->>'pump1')::NUMERIC)) as values, 'étatpompe' as metric FROM metrics  WHERE user_id=3 and  $__timeFilter(\"time\") GROUP BY metrics.data, metrics.time ORDER BY metrics.time\n\n-- SELECT $__time(\"time\"),((data->>'pump1')::NUMERIC) as values, 'étatpompe' as metric FROM metrics "
    }
   ]
  },
  {
   "title": "Température",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(\"time\",$__interval,previous),AVG(((data->>'temp1')::NUMERIC)) as values, 'toit' as metric FROM metrics  WHERE user_id=3  and $__timeFilter(\"time\") GROUP BY metrics.data, metrics.time ORDER BY metrics.time\n"
    },
    {
     "rawSql": "SELECT $__timeGroupAlias(\"time\",$__interval,previous),AVG(((data->>'temp2')::NUMERIC)) as values, 'basballon' as metric FROM metrics  WHERE user_id=3  and $__timeFilter(\"time\") GROUP BY metrics.data, metrics.time ORDER BY metrics.time\n"
    },
    {
     "rawSql": "SELECT $__timeGroupAlias(\"time\",$__interval,previous),AVG(((data->>'temp3')::NUMERIC)) as values, 'hautballon' as metric FROM metrics  WHERE user_id=3  and $__timeFilter(\"time\") GROUP BY metrics.data, metrics.time ORDER BY metrics.time\n"
    },
    {
     "rawSql": "SELECT $__timeGroupAlias(\"time\",$__interval,previous),AVG(((data->>'temp4')::NUMERIC)) as values, 'echange' as metric FROM metrics  WHERE user_id=3  and $__timeFilter(\"time\") GROUP BY metrics.data, metrics.time ORDER BY metrics.time"
    }
   ]
  }
 ]
}